// Decompiled with JetBrains decompiler
// Type: ELIS.ELISConfiguration.GemeindeKennzahl
// Assembly: ELISConfigBase, Version=3.3.7468.42109, Culture=neutral, PublicKeyToken=null
// MVID: BE38FD42-018D-4617-86E9-4344F3F52349
// Assembly location: C:\Users\Haunschmied.Bastian\Documents\GitHub\Feuerwehr-Tools\FFF_Elis\FFF_Elis\libs\ELISConfigBase.dll

using System;
using System.Collections.Generic;

#nullable disable
namespace ELIS.ELISConfiguration
{
  public class GemeindeKennzahl
  {
    public long GemeindeNr { get; set; }

    public string GemeindeName { get; set; }

    public long BezirkNr { get; set; }

    public string BezirkName { get; set; }

    internal GemeindeKennzahl(long GemNr, string GemName, long BezNr, string BezName)
    {
      this.GemeindeNr = GemNr;
      this.GemeindeName = GemName;
      this.BezirkNr = BezNr;
      this.BezirkName = BezName;
    }

    public static GemeindeKennzahl getByGemeindeNummer(long GemNr, GemeindeKennzahlLand region)
    {
      return region == GemeindeKennzahlLand.OOE ? GemeindeKennzahl.Liste.Find((Predicate<GemeindeKennzahl>) (x => x.GemeindeNr == GemNr)) : GemeindeKennzahl.ListeDE.Find((Predicate<GemeindeKennzahl>) (x => x.GemeindeNr == GemNr));
    }

    public static GemeindeKennzahl getByGemeindeNummer(string GemNr, GemeindeKennzahlLand region)
    {
      if (string.IsNullOrEmpty(GemNr))
        return (GemeindeKennzahl) null;
      long gkVal = 0;
      if (!long.TryParse(GemNr, out gkVal))
        return (GemeindeKennzahl) null;
      return region == GemeindeKennzahlLand.OOE ? GemeindeKennzahl.Liste.Find((Predicate<GemeindeKennzahl>) (x => x.GemeindeNr == gkVal)) : GemeindeKennzahl.ListeDE.Find((Predicate<GemeindeKennzahl>) (x => x.GemeindeNr == gkVal));
    }

    public override string ToString()
    {
      return this.GemeindeNr.ToString() + " " + this.GemeindeName + " (" + this.BezirkNr.ToString() + "-" + this.BezirkName + ")";
    }

    public override bool Equals(object obj)
    {
      return obj is GemeindeKennzahl gemeindeKennzahl && gemeindeKennzahl.GemeindeNr == this.GemeindeNr;
    }

    public override int GetHashCode() => base.GetHashCode();

    public static List<GemeindeKennzahl> Liste
    {
      get
      {
        return new List<GemeindeKennzahl>()
        {
          new GemeindeKennzahl(40101L, "Linz", 401L, "Linz"),
          new GemeindeKennzahl(40201L, "Steyr", 402L, "Steyr"),
          new GemeindeKennzahl(40301L, "Wels", 403L, "Wels"),
          new GemeindeKennzahl(40401L, "Altheim", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40402L, "Aspach", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40403L, "Auerbach", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40404L, "Braunau am Inn", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40405L, "Burgkirchen", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40406L, "Eggelsberg", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40407L, "Feldkirchen bei Mattighofen", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40408L, "Franking", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40409L, "Geretsberg", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40410L, "Gilgenberg am Weilhart", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40411L, "Haigermoos", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40412L, "Handenberg", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40413L, "Helpfau-Uttendorf", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40414L, "Hochburg-Ach", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40415L, "Höhnhart", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40416L, "Jeging", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40417L, "Kirchberg bei Mattighofen", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40418L, "Lengau", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40419L, "Lochen am See", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40420L, "Maria Schmolln", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40421L, "Mattighofen", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40422L, "Mauerkirchen", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40423L, "Mining", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40424L, "Moosbach", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40425L, "Moosdorf", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40426L, "Munderfing", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40427L, "Neukirchen an der Enknach", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40428L, "Ostermiething", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40429L, "Palting", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40430L, "Perwang am Grabensee", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40431L, "Pfaffstätt", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40432L, "Pischelsdorf am Engelbach", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40433L, "Polling im Innkreis", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40434L, "Roßbach", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40435L, "Sankt Georgen am Fillmannsbach", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40436L, "Sankt Johann am Walde", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40437L, "Sankt Pantaleon", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40438L, "Sankt Peter am Hart", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40439L, "Sankt Radegund", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40440L, "Sankt Veit im Innkreis", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40441L, "Schalchen", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40442L, "Schwand im Innkreis", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40443L, "Tarsdorf", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40444L, "Treubach", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40445L, "Überackern", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40446L, "Weng im Innkreis", 404L, "Braunau am Inn"),
          new GemeindeKennzahl(40501L, "Alkoven", 405L, "Eferding"),
          new GemeindeKennzahl(40502L, "Aschach an der Donau", 405L, "Eferding"),
          new GemeindeKennzahl(40503L, "Eferding", 405L, "Eferding"),
          new GemeindeKennzahl(40504L, "Fraham", 405L, "Eferding"),
          new GemeindeKennzahl(40505L, "Haibach ob der Donau", 405L, "Eferding"),
          new GemeindeKennzahl(40506L, "Hartkirchen", 405L, "Eferding"),
          new GemeindeKennzahl(40507L, "Hinzenbach", 405L, "Eferding"),
          new GemeindeKennzahl(40508L, "Prambachkirchen", 405L, "Eferding"),
          new GemeindeKennzahl(40509L, "Pupping", 405L, "Eferding"),
          new GemeindeKennzahl(40510L, "Sankt Marienkirchen an der Polsenz", 405L, "Eferding"),
          new GemeindeKennzahl(40511L, "Scharten", 405L, "Eferding"),
          new GemeindeKennzahl(40512L, "Stroheim", 405L, "Eferding"),
          new GemeindeKennzahl(40601L, "Freistadt", 406L, "Freistadt"),
          new GemeindeKennzahl(40602L, "Grünbach", 406L, "Freistadt"),
          new GemeindeKennzahl(40603L, "Gutau", 406L, "Freistadt"),
          new GemeindeKennzahl(40604L, "Hagenberg im Mühlkreis", 406L, "Freistadt"),
          new GemeindeKennzahl(40605L, "Hirschbach im Mühlkreis", 406L, "Freistadt"),
          new GemeindeKennzahl(40606L, "Kaltenberg", 406L, "Freistadt"),
          new GemeindeKennzahl(40607L, "Kefermarkt", 406L, "Freistadt"),
          new GemeindeKennzahl(40608L, "Königswiesen", 406L, "Freistadt"),
          new GemeindeKennzahl(40609L, "Lasberg", 406L, "Freistadt"),
          new GemeindeKennzahl(40610L, "Leopoldschlag", 406L, "Freistadt"),
          new GemeindeKennzahl(40611L, "Liebenau", 406L, "Freistadt"),
          new GemeindeKennzahl(40612L, "Neumarkt im Mühlkreis", 406L, "Freistadt"),
          new GemeindeKennzahl(40613L, "Pierbach", 406L, "Freistadt"),
          new GemeindeKennzahl(40614L, "Pregarten", 406L, "Freistadt"),
          new GemeindeKennzahl(40615L, "Rainbach im Mühlkreis", 406L, "Freistadt"),
          new GemeindeKennzahl(40616L, "Sandl", 406L, "Freistadt"),
          new GemeindeKennzahl(40617L, "Sankt Leonhard bei Freistadt", 406L, "Freistadt"),
          new GemeindeKennzahl(40618L, "Sankt Oswald bei Freistadt", 406L, "Freistadt"),
          new GemeindeKennzahl(40619L, "Schönau im Mühlkreis", 406L, "Freistadt"),
          new GemeindeKennzahl(40620L, "Tragwein", 406L, "Freistadt"),
          new GemeindeKennzahl(40621L, "Unterweißenbach", 406L, "Freistadt"),
          new GemeindeKennzahl(40622L, "Unterweitersdorf", 406L, "Freistadt"),
          new GemeindeKennzahl(40623L, "Waldburg", 406L, "Freistadt"),
          new GemeindeKennzahl(40624L, "Wartberg ob der Aist", 406L, "Freistadt"),
          new GemeindeKennzahl(40625L, "Weitersfelden", 406L, "Freistadt"),
          new GemeindeKennzahl(40626L, "Windhaag bei Freistadt", 406L, "Freistadt"),
          new GemeindeKennzahl(40627L, "Bad Zell", 406L, "Freistadt"),
          new GemeindeKennzahl(40701L, "Altmünster", 407L, "Gmunden"),
          new GemeindeKennzahl(40702L, "Bad Goisern", 407L, "Gmunden"),
          new GemeindeKennzahl(40703L, "Bad Ischl", 407L, "Gmunden"),
          new GemeindeKennzahl(40704L, "Ebensee", 407L, "Gmunden"),
          new GemeindeKennzahl(40705L, "Gmunden", 407L, "Gmunden"),
          new GemeindeKennzahl(40706L, "Gosau", 407L, "Gmunden"),
          new GemeindeKennzahl(40707L, "Grünau im Almtal", 407L, "Gmunden"),
          new GemeindeKennzahl(40708L, "Gschwandt", 407L, "Gmunden"),
          new GemeindeKennzahl(40709L, "Hallstatt", 407L, "Gmunden"),
          new GemeindeKennzahl(40710L, "Kirchham", 407L, "Gmunden"),
          new GemeindeKennzahl(40711L, "Laakirchen", 407L, "Gmunden"),
          new GemeindeKennzahl(40712L, "Obertraun", 407L, "Gmunden"),
          new GemeindeKennzahl(40713L, "Ohlsdorf", 407L, "Gmunden"),
          new GemeindeKennzahl(40714L, "Pinsdorf", 407L, "Gmunden"),
          new GemeindeKennzahl(40715L, "Roitham", 407L, "Gmunden"),
          new GemeindeKennzahl(40716L, "Sankt Konrad", 407L, "Gmunden"),
          new GemeindeKennzahl(40717L, "Sankt Wolfgang im Salzkammergut", 407L, "Gmunden"),
          new GemeindeKennzahl(40718L, "Traunkirchen", 407L, "Gmunden"),
          new GemeindeKennzahl(40719L, "Scharnstein", 407L, "Gmunden"),
          new GemeindeKennzahl(40720L, "Vorchdorf", 407L, "Gmunden"),
          new GemeindeKennzahl(40801L, "Aistersheim", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40802L, "Bad Schallerbach", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40803L, "Bruck-Waasen", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40804L, "Eschenau im Hausruckkreis", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40805L, "Gallspach", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40806L, "Gaspoltshofen", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40807L, "Geboltskirchen", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40808L, "Grieskirchen", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40809L, "Haag am Hausruck", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40810L, "Heiligenberg", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40811L, "Hofkirchen an der Trattnach", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40812L, "Kallham", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40813L, "Kematen am Innbach", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40814L, "Meggenhofen", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40815L, "Michaelnbach", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40816L, "Natternbach", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40817L, "Neukirchen am Walde", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40818L, "Neumarkt im Hausruckkreis", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40819L, "Peuerbach", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40820L, "Pötting", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40821L, "Pollham", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40822L, "Pram", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40823L, "Rottenbach", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40824L, "Sankt Agatha", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40825L, "Sankt Georgen bei Grieskirchen", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40826L, "Sankt Thomas", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40827L, "Schlüßlberg", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40828L, "Steegen", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40829L, "Taufkirchen an der Trattnach", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40830L, "Tollet", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40831L, "Waizenkirchen", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40832L, "Wallern an der Trattnach", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40833L, "Weibern", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40834L, "Wendling", 408L, "Grieskirchen"),
          new GemeindeKennzahl(40901L, "Edlbach", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40902L, "Grünburg", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40903L, "Hinterstoder", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40904L, "Inzersdorf im Kremstal", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40905L, "Kirchdorf an der Krems", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40906L, "Klaus an der Pyhrnbahn", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40907L, "Kremsmünster", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40908L, "Micheldorf in Oberösterreich", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40909L, "Molln", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40910L, "Nußbach", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40911L, "Oberschlierbach", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40912L, "Pettenbach", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40913L, "Ried im Traunkreis", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40914L, "Rosenau am Hengstpaß", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40915L, "Roßleithen", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40916L, "Sankt Pankraz", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40917L, "Schlierbach", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40918L, "Spital am Pyhrn", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40919L, "Steinbach am Ziehberg", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40920L, "Steinbach an der Steyr", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40921L, "Vorderstoder", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40922L, "Wartberg an der Krems", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(40923L, "Windischgarsten", 409L, "Kirchdorf an der Krems"),
          new GemeindeKennzahl(41001L, "Allhaming", 410L, "Linz-Land"),
          new GemeindeKennzahl(41002L, "Ansfelden", 410L, "Linz-Land"),
          new GemeindeKennzahl(41003L, "Asten", 410L, "Linz-Land"),
          new GemeindeKennzahl(41004L, "Eggendorf im Traunkreis", 410L, "Linz-Land"),
          new GemeindeKennzahl(41005L, "Enns", 410L, "Linz-Land"),
          new GemeindeKennzahl(41006L, "Hargelsberg", 410L, "Linz-Land"),
          new GemeindeKennzahl(41007L, "Hörsching", 410L, "Linz-Land"),
          new GemeindeKennzahl(41008L, "Hofkirchen im Traunkreis", 410L, "Linz-Land"),
          new GemeindeKennzahl(41009L, "Kematen an der Krems", 410L, "Linz-Land"),
          new GemeindeKennzahl(41010L, "Kirchberg-Thening", 410L, "Linz-Land"),
          new GemeindeKennzahl(41011L, "Kronstorf", 410L, "Linz-Land"),
          new GemeindeKennzahl(41012L, "Leonding", 410L, "Linz-Land"),
          new GemeindeKennzahl(41013L, "Markt Sankt Florian", 410L, "Linz-Land"),
          new GemeindeKennzahl(41014L, "Neuhofen an der Krems", 410L, "Linz-Land"),
          new GemeindeKennzahl(41015L, "Niederneukirchen", 410L, "Linz-Land"),
          new GemeindeKennzahl(41016L, "Oftering", 410L, "Linz-Land"),
          new GemeindeKennzahl(41017L, "Pasching", 410L, "Linz-Land"),
          new GemeindeKennzahl(41018L, "Piberbach", 410L, "Linz-Land"),
          new GemeindeKennzahl(41019L, "Pucking", 410L, "Linz-Land"),
          new GemeindeKennzahl(41020L, "Sankt Marien", 410L, "Linz-Land"),
          new GemeindeKennzahl(41021L, "Traun", 410L, "Linz-Land"),
          new GemeindeKennzahl(41022L, "Wilhering", 410L, "Linz-Land"),
          new GemeindeKennzahl(41101L, "Allerheiligen im Mühlkreis", 411L, "Perg"),
          new GemeindeKennzahl(41102L, "Arbing", 411L, "Perg"),
          new GemeindeKennzahl(41103L, "Baumgartenberg", 411L, "Perg"),
          new GemeindeKennzahl(41104L, "Dimbach", 411L, "Perg"),
          new GemeindeKennzahl(41105L, "Grein", 411L, "Perg"),
          new GemeindeKennzahl(41106L, "Katsdorf", 411L, "Perg"),
          new GemeindeKennzahl(41107L, "Klam", 411L, "Perg"),
          new GemeindeKennzahl(41108L, "Bad Kreuzen", 411L, "Perg"),
          new GemeindeKennzahl(41109L, "Langenstein", 411L, "Perg"),
          new GemeindeKennzahl(41110L, "Luftenberg an der Donau", 411L, "Perg"),
          new GemeindeKennzahl(41111L, "Mauthausen", 411L, "Perg"),
          new GemeindeKennzahl(41112L, "Mitterkirchen im Machland", 411L, "Perg"),
          new GemeindeKennzahl(41113L, "Münzbach", 411L, "Perg"),
          new GemeindeKennzahl(41114L, "Naarn im Machlande", 411L, "Perg"),
          new GemeindeKennzahl(41115L, "Pabneukirchen", 411L, "Perg"),
          new GemeindeKennzahl(41116L, "Perg", 411L, "Perg"),
          new GemeindeKennzahl(41117L, "Rechberg", 411L, "Perg"),
          new GemeindeKennzahl(41118L, "Ried in der Riedmark", 411L, "Perg"),
          new GemeindeKennzahl(41119L, "Sankt Georgen am Walde", 411L, "Perg"),
          new GemeindeKennzahl(41120L, "Sankt Georgen an der Gusen", 411L, "Perg"),
          new GemeindeKennzahl(41121L, "Sankt Nikola an der Donau", 411L, "Perg"),
          new GemeindeKennzahl(41122L, "Sankt Thomas am Blasenstein", 411L, "Perg"),
          new GemeindeKennzahl(41123L, "Saxen", 411L, "Perg"),
          new GemeindeKennzahl(41124L, "Schwertberg", 411L, "Perg"),
          new GemeindeKennzahl(41125L, "Waldhausen im Strudengau", 411L, "Perg"),
          new GemeindeKennzahl(41126L, "Windhaag bei Perg", 411L, "Perg"),
          new GemeindeKennzahl(41201L, "Andrichsfurt", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41202L, "Antiesenhofen", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41203L, "Aurolzmünster", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41204L, "Eberschwang", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41205L, "Eitzing", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41206L, "Geiersberg", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41207L, "Geinberg", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41208L, "Gurten", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41209L, "Hohenzell", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41210L, "Kirchdorf am Inn", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41211L, "Kirchheim im Innkreis", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41212L, "Lambrechten", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41213L, "Lohnsburg am Kobernaußerwald", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41214L, "Mehrnbach", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41215L, "Mettmach", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41216L, "Mörschwang", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41217L, "Mühlheim am Inn", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41218L, "Neuhofen im Innkreis", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41219L, "Obernberg am Inn", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41220L, "Ort im Innkreis", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41221L, "Pattigham", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41222L, "Peterskirchen", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41223L, "Pramet", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41224L, "Reichersberg", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41225L, "Ried im Innkreis", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41226L, "Sankt Georgen bei Obernberg am Inn", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41227L, "Sankt Marienkirchen am Hausruck", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41228L, "Sankt Martin im Innkreis", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41229L, "Schildorn", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41230L, "Senftenbach", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41231L, "Taiskirchen im Innkreis", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41232L, "Tumeltsham", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41233L, "Utzenaich", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41234L, "Waldzell", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41235L, "Weilbach", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41236L, "Wippenham", 412L, "Ried im Innkreis"),
          new GemeindeKennzahl(41301L, "Afiesl", 413L, "Rohrbach"),
          new GemeindeKennzahl(41302L, "Ahorn", 413L, "Rohrbach"),
          new GemeindeKennzahl(41303L, "Aigen im Mühlkreis", 413L, "Rohrbach"),
          new GemeindeKennzahl(41304L, "Altenfelden", 413L, "Rohrbach"),
          new GemeindeKennzahl(41305L, "Arnreit", 413L, "Rohrbach"),
          new GemeindeKennzahl(41306L, "Atzesberg", 413L, "Rohrbach"),
          new GemeindeKennzahl(41307L, "Auberg", 413L, "Rohrbach"),
          new GemeindeKennzahl(41308L, "Berg bei Rohrbach", 413L, "Rohrbach"),
          new GemeindeKennzahl(41309L, "Haslach an der Mühl", 413L, "Rohrbach"),
          new GemeindeKennzahl(41310L, "Helfenberg", 413L, "Rohrbach"),
          new GemeindeKennzahl(41311L, "Hörbich", 413L, "Rohrbach"),
          new GemeindeKennzahl(41312L, "Hofkirchen im Mühlkreis", 413L, "Rohrbach"),
          new GemeindeKennzahl(41313L, "Julbach", 413L, "Rohrbach"),
          new GemeindeKennzahl(41314L, "Kirchberg ob der Donau", 413L, "Rohrbach"),
          new GemeindeKennzahl(41315L, "Klaffer am Hochficht", 413L, "Rohrbach"),
          new GemeindeKennzahl(41316L, "Kleinzell im Mühlkreis", 413L, "Rohrbach"),
          new GemeindeKennzahl(41317L, "Kollerschlag", 413L, "Rohrbach"),
          new GemeindeKennzahl(41318L, "Lembach im Mühlkreis", 413L, "Rohrbach"),
          new GemeindeKennzahl(41319L, "Lichtenau im Mühlkreis", 413L, "Rohrbach"),
          new GemeindeKennzahl(41320L, "Nebelberg", 413L, "Rohrbach"),
          new GemeindeKennzahl(41321L, "Neufelden", 413L, "Rohrbach"),
          new GemeindeKennzahl(41322L, "Niederkappel", 413L, "Rohrbach"),
          new GemeindeKennzahl(41323L, "Niederwaldkirchen", 413L, "Rohrbach"),
          new GemeindeKennzahl(41324L, "Oberkappel", 413L, "Rohrbach"),
          new GemeindeKennzahl(41325L, "Oepping", 413L, "Rohrbach"),
          new GemeindeKennzahl(41326L, "Peilstein im Mühlviertel", 413L, "Rohrbach"),
          new GemeindeKennzahl(41327L, "Pfarrkirchen im Mühlkreis", 413L, "Rohrbach"),
          new GemeindeKennzahl(41328L, "Putzleinsdorf", 413L, "Rohrbach"),
          new GemeindeKennzahl(41329L, "Neustift im Mühlkreis", 413L, "Rohrbach"),
          new GemeindeKennzahl(41330L, "Rohrbach in Oberösterreich", 413L, "Rohrbach"),
          new GemeindeKennzahl(41331L, "Sankt Johann am Wimberg", 413L, "Rohrbach"),
          new GemeindeKennzahl(41332L, "Sankt Martin im Mühlkreis", 413L, "Rohrbach"),
          new GemeindeKennzahl(41333L, "Sankt Oswald bei Haslach", 413L, "Rohrbach"),
          new GemeindeKennzahl(41334L, "Sankt Peter am Wimberg", 413L, "Rohrbach"),
          new GemeindeKennzahl(41335L, "Sankt Stefan am Walde", 413L, "Rohrbach"),
          new GemeindeKennzahl(41336L, "Sankt Ulrich im Mühlkreis", 413L, "Rohrbach"),
          new GemeindeKennzahl(41337L, "Sankt Veit im Mühlkreis", 413L, "Rohrbach"),
          new GemeindeKennzahl(41338L, "Sarleinsbach", 413L, "Rohrbach"),
          new GemeindeKennzahl(41339L, "Schlägl", 413L, "Rohrbach"),
          new GemeindeKennzahl(41340L, "Schönegg", 413L, "Rohrbach"),
          new GemeindeKennzahl(41341L, "Schwarzenberg am Böhmerwald", 413L, "Rohrbach"),
          new GemeindeKennzahl(41342L, "Ulrichsberg", 413L, "Rohrbach"),
          new GemeindeKennzahl(41401L, "Altschwendt", 414L, "Schärding"),
          new GemeindeKennzahl(41402L, "Andorf", 414L, "Schärding"),
          new GemeindeKennzahl(41403L, "Brunnenthal", 414L, "Schärding"),
          new GemeindeKennzahl(41404L, "Diersbach", 414L, "Schärding"),
          new GemeindeKennzahl(41405L, "Dorf an der Pram", 414L, "Schärding"),
          new GemeindeKennzahl(41406L, "Eggerding", 414L, "Schärding"),
          new GemeindeKennzahl(41407L, "Engelhartszell", 414L, "Schärding"),
          new GemeindeKennzahl(41408L, "Enzenkirchen", 414L, "Schärding"),
          new GemeindeKennzahl(41409L, "Esternberg", 414L, "Schärding"),
          new GemeindeKennzahl(41410L, "Freinberg", 414L, "Schärding"),
          new GemeindeKennzahl(41411L, "Kopfing im Innkreis", 414L, "Schärding"),
          new GemeindeKennzahl(41412L, "Mayrhof", 414L, "Schärding"),
          new GemeindeKennzahl(41413L, "Münzkirchen", 414L, "Schärding"),
          new GemeindeKennzahl(41414L, "Raab", 414L, "Schärding"),
          new GemeindeKennzahl(41415L, "Rainbach im Innkreis", 414L, "Schärding"),
          new GemeindeKennzahl(41416L, "Riedau", 414L, "Schärding"),
          new GemeindeKennzahl(41417L, "Sankt Aegidi", 414L, "Schärding"),
          new GemeindeKennzahl(41418L, "Sankt Florian am Inn", 414L, "Schärding"),
          new GemeindeKennzahl(41419L, "Sankt Marienkirchen bei Schärding", 414L, "Schärding"),
          new GemeindeKennzahl(41420L, "Sankt Roman", 414L, "Schärding"),
          new GemeindeKennzahl(41421L, "Sankt Willibald", 414L, "Schärding"),
          new GemeindeKennzahl(41422L, "Schärding", 414L, "Schärding"),
          new GemeindeKennzahl(41423L, "Schardenberg", 414L, "Schärding"),
          new GemeindeKennzahl(41424L, "Sigharting", 414L, "Schärding"),
          new GemeindeKennzahl(41425L, "Suben", 414L, "Schärding"),
          new GemeindeKennzahl(41426L, "Taufkirchen an der Pram", 414L, "Schärding"),
          new GemeindeKennzahl(41427L, "Vichtenstein", 414L, "Schärding"),
          new GemeindeKennzahl(41428L, "Waldkirchen am Wesen", 414L, "Schärding"),
          new GemeindeKennzahl(41429L, "Wernstein am Inn", 414L, "Schärding"),
          new GemeindeKennzahl(41430L, "Zell an der Pram", 414L, "Schärding"),
          new GemeindeKennzahl(41501L, "Adlwang", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41502L, "Aschach an der Steyr", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41503L, "Bad Hall", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41504L, "Dietach", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41505L, "Gaflenz", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41506L, "Garsten", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41507L, "Großraming", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41508L, "Laussa", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41509L, "Losenstein", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41510L, "Maria Neustift", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41511L, "Pfarrkirchen bei Bad Hall", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41512L, "Reichraming", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41513L, "Rohr im Kremstal", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41514L, "Sankt Ulrich bei Steyr", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41515L, "Schiedlberg", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41516L, "Sierning", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41517L, "Ternberg", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41518L, "Waldneukirchen", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41521L, "Wolfern", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41522L, "Weyer", 415L, "Steyr-Land"),
          new GemeindeKennzahl(41601L, "Alberndorf in der Riedmark", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41602L, "Altenberg bei Linz", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41603L, "Bad Leonfelden", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41604L, "Eidenberg", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41605L, "Engerwitzdorf", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41606L, "Feldkirchen an der Donau", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41607L, "Gallneukirchen", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41608L, "Goldwörth", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41609L, "Gramastetten", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41610L, "Haibach im Mühlkreis", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41611L, "Hellmonsödt", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41612L, "Herzogsdorf", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41613L, "Kirchschlag bei Linz", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41614L, "Lichtenberg", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41615L, "Oberneukirchen", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41616L, "Ottenschlag im Mühlkreis", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41617L, "Ottensheim", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41618L, "Puchenau", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41619L, "Reichenau im Mühlkreis", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41620L, "Reichenthal", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41621L, "Sankt Gotthard im Mühlkreis", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41622L, "Schenkenfelden", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41623L, "Sonnberg im Mühlkreis", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41624L, "Steyregg", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41625L, "Vorderweißenbach", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41626L, "Walding", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41627L, "Zwettl an der Rodl", 416L, "Urfahr-Umgebung"),
          new GemeindeKennzahl(41701L, "Ampflwang im Hausruckwald", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41702L, "Attersee", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41703L, "Attnang-Puchheim", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41704L, "Atzbach", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41705L, "Aurach am Hongar", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41706L, "Berg im Attergau", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41707L, "Desselbrunn", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41708L, "Fornach", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41709L, "Frankenburg am Hausruck", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41710L, "Frankenmarkt", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41711L, "Gampern", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41712L, "Innerschwand", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41713L, "Lenzing", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41714L, "Manning", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41715L, "Mondsee", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41716L, "Neukirchen an der Vöckla", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41717L, "Niederthalheim", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41718L, "Nußdorf am Attersee", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41719L, "Oberhofen am Irrsee", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41720L, "Oberndorf bei Schwanenstadt", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41721L, "Oberwang", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41722L, "Ottnang am Hausruck", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41723L, "Pfaffing", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41724L, "Pilsbach", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41725L, "Pitzenberg", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41726L, "Pöndorf", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41727L, "Puchkirchen am Trattberg", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41728L, "Pühret", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41729L, "Redleiten", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41730L, "Redlham", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41731L, "Regau", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41732L, "Rüstorf", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41733L, "Rutzenham", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41734L, "Sankt Georgen im Attergau", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41735L, "Sankt Lorenz", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41736L, "Schlatt", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41737L, "Schörfling am Attersee", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41738L, "Schwanenstadt", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41739L, "Seewalchen am Attersee", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41740L, "Steinbach am Attersee", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41741L, "Straß im Attergau", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41742L, "Tiefgraben", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41743L, "Timelkam", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41744L, "Ungenach", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41745L, "Unterach am Attersee", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41746L, "Vöcklabruck", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41747L, "Vöcklamarkt", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41748L, "Weißenkirchen im Attergau", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41749L, "Weyregg am Attersee", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41750L, "Wolfsegg am Hausruck", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41751L, "Zell am Moos", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41752L, "Zell am Pettenfirst", 417L, "Vöcklabruck"),
          new GemeindeKennzahl(41801L, "Aichkirchen", 418L, "Wels-Land"),
          new GemeindeKennzahl(41802L, "Bachmanning", 418L, "Wels-Land"),
          new GemeindeKennzahl(41803L, "Bad Wimsbach-Neydharting", 418L, "Wels-Land"),
          new GemeindeKennzahl(41804L, "Buchkirchen", 418L, "Wels-Land"),
          new GemeindeKennzahl(41805L, "Eberstalzell", 418L, "Wels-Land"),
          new GemeindeKennzahl(41806L, "Edt bei Lambach", 418L, "Wels-Land"),
          new GemeindeKennzahl(41807L, "Fischlham", 418L, "Wels-Land"),
          new GemeindeKennzahl(41808L, "Gunskirchen", 418L, "Wels-Land"),
          new GemeindeKennzahl(41809L, "Holzhausen", 418L, "Wels-Land"),
          new GemeindeKennzahl(41810L, "Krenglbach", 418L, "Wels-Land"),
          new GemeindeKennzahl(41811L, "Lambach", 418L, "Wels-Land"),
          new GemeindeKennzahl(41812L, "Marchtrenk", 418L, "Wels-Land"),
          new GemeindeKennzahl(41813L, "Neukirchen bei Lambach", 418L, "Wels-Land"),
          new GemeindeKennzahl(41814L, "Offenhausen", 418L, "Wels-Land"),
          new GemeindeKennzahl(41815L, "Pennewang", 418L, "Wels-Land"),
          new GemeindeKennzahl(41816L, "Pichl bei Wels", 418L, "Wels-Land"),
          new GemeindeKennzahl(41817L, "Sattledt", 418L, "Wels-Land"),
          new GemeindeKennzahl(41818L, "Schleißheim", 418L, "Wels-Land"),
          new GemeindeKennzahl(41819L, "Sipbachzell", 418L, "Wels-Land"),
          new GemeindeKennzahl(41820L, "Stadl-Paura", 418L, "Wels-Land"),
          new GemeindeKennzahl(41821L, "Steinerkirchen an der Traun", 418L, "Wels-Land"),
          new GemeindeKennzahl(41822L, "Steinhaus", 418L, "Wels-Land"),
          new GemeindeKennzahl(41823L, "Thalheim bei Wels", 418L, "Wels-Land"),
          new GemeindeKennzahl(41824L, "Weißkirchen an der Traun", 418L, "Wels-Land")
        };
      }
    }

    public static List<GemeindeKennzahl> ListeDE
    {
      get
      {
        return new List<GemeindeKennzahl>()
        {
          new GemeindeKennzahl(62001L, "Ahrensburg", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62003L, "Badendorf", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62004L, "Bad Oldesloe", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62005L, "Bargfeld-Stegen", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62006L, "Bargteheide", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62008L, "Barnitz", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62009L, "Barsbüttel", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62011L, "Braak", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62014L, "Delingsdorf", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62016L, "Elmenhorst", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62018L, "Glinde", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62019L, "Grabau", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62020L, "Grande", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62021L, "Grönwohld", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62022L, "Großensee", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62023L, "Großhansdorf", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62025L, "Hamberge", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62026L, "Hamfelde", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62027L, "Hammoor", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62031L, "Heidekamp", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62032L, "Heilshoop", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62035L, "Hoisdorf", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62036L, "Jersbek", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62039L, "Klein Wesenberg", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62040L, "Köthel", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62045L, "Lütjensee", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62046L, "Meddewade", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62048L, "Mönkhagen-Langniendorf", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62050L, "Neritz", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62051L, "Nienwohld", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62053L, "Oststeinbek", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62056L, "Pölitz", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62058L, "Rausdorf", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62059L, "Pöhls", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62060L, "Reinbek", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62061L, "Reinfeld", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62062L, "Rethwischdorf", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62065L, "Rümpel", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62069L, "Siek", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62071L, "Stapelfeld", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62076L, "Tangstedt", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62078L, "Todendorf", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62081L, "Tremsbüttel", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62082L, "Trittau", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62083L, "Westerau", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62086L, "Witzhave", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62087L, "Zarpen", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62088L, "Brunsbek", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62089L, "Lasbek", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62090L, "Ammersbek", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62091L, "Steinburg", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62092L, "Travenbrück", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62093L, "Steinfeld", 620L, "Schleswig-Holstein"),
          new GemeindeKennzahl(62094L, "Wesenberg", 620L, "Schleswig-Holstein")
        };
      }
    }
  }
}
